### ISSUE TITLE
<lang>.po headers are not preserved

### ISSUE THREAD

**Issue by max-l** [beck/git-po-merge#2]
Awesome tool btw ! 
much easier to install and use than other alternatives I have tried.

I have a project whith a fr.po that has a header similar to this :

<pre>
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: \n"
"PO-Revision-Date: 2015-06-27 22:13-0500\n"
"Language-Team: French\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Poedit 1.8.1\n"
</pre>

After running a git-po-merge, the heades become : 

<pre>
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"MIME-Version: 1.0\n"
</pre>

I work around this by manually replacing the fields, but it would be nice if git-po-merged preserved headers

**Comment by beck** [comment]
> it would be nice if git-po-merged preserved headers

Apologies, this is a bit of personal bias (and laziness) leaking into the tool. Whenever I see `"POT-Creation-Date: \n"` I think, "well this is just useless, especially when using version control."

`"PO-Revision-Date: 2015-06-27 22:13-0500\n"` is troublesome because it is often a source of merge conflict.

But I totally agree, the tool should not botch headers.

I'm not sure when I'll get some free time to squash this bug but it makes me happy to know someone else is using this tool :smile:

**Comment by joh-klein** [comment]
We want to use this tool to, but can't since the missing language header prevents us from using the merged *.po files (e.g. in PoEdit). I wrote a workaround, hopefully you can take a look at it in the near future?!
